### ISSUE TITLE
Unable to start Daemon

### ISSUE THREAD

**Issue by mspieth376** [V-Paranoiaque/vca#4]
Running under Debian Wheezy I receive the following error upon startup of the daemon.

# /etc/init.d/vcadaemon start
Starting vcadaemon: 
Traceback (most recent call last):
  File "/usr/share/vca/daemon/vcadaemon.py", line 13, in <module>
    from server import Server 
  File "/usr/share/vca/daemon/server.py", line 9, in <module>
    from vps import Vps 
  File "/usr/share/vca/daemon/vps.py", line 6, in <module>
    import dropbox
  File "/usr/local/lib/python3.2/dist-packages/dropbox/__init__.py", line 3, in <module>
    from .dropbox import __version__
  File "/usr/local/lib/python3.2/dist-packages/dropbox/dropbox.py", line 18, in <module>
    from .base import DropboxBase
  File "/usr/local/lib/python3.2/dist-packages/dropbox/base.py", line 7, in <module>
    from . import (
  File "/usr/local/lib/python3.2/dist-packages/dropbox/files.py", line 3532
    (u'file',): bv.Struct(FileMetadata),
           ^
SyntaxError: invalid syntax

**Comment by V-Paranoiaque** [comment]
I think it's a problem with dropbox sdk and python 3.2.
You can disable this feature in vps.py, line 6 comment "import dropbox".

**Comment by V-Paranoiaque** [comment]
Fixed, upgrade and don't configure Dropbox.
It's a bug in Dropbox sdk.
